# Generated by Django 4.2 on 2023-06-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tareas",
            name="datecomplete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
